INSERT INTO MEMBER VALUES ('김지형',25);

SELECT * FROM MEMBER;

-- DDL CREATE 생성, ALTER
-- ALTER TABLE MEMBER DROP COLUMN AGE;
UPDATE MEMBER SET AGE=NULL;

ALTER TABLE MEMBER MODIFY AGE NUMBER(3);

-- UPDATE MEMBER SET AGE=2500 WHERE NAME='김지형';
-- number(3) -999~999
UPDATE MEMBER SET AGE=25 WHERE NAME='김지형';
UPDATE MEMBER SET AGE=-100 WHERE NAME='이지형';

-- 칼럼의 제약조건을 주는 것은 칼럼 수정이 아니고 제약 조건 등록
UPDATE MEMBER SET AGE=20 WHERE NAME='이지형';
ALTER TABLE MEMBER ADD CONSTRAINT age_check CHECK ( AGE>=0 AND AGE<=200 );

ALTER TABLE MEMBER DROP CONSTRAINT age_check;
-- 제약조건 삭제
INSERT INTO MEMBER ( age) VALUES (39);
-- DELETE FROM TABLE WHERE
DELETE FROM MEMBER WHERE AGE=39;
-- ****** ALTER 를 사용할 일은 별로 없다!!
-- ALTER TABLE MEMBER ADD CONSTRAINT name_not_null
ALTER TABLE MEMBER MODIFY (name NOT NULL );
INSERT INTO MEMBER VALUES ('최경민',39);

ALTER TABLE MEMBER ADD ID NUMBER(5);

DELETE FROM MEMBER WHERE NAME='김지형';

ALTER TABLE MEMBER ADD CONSTRAINT pk_member PRIMARY KEY (id);

INSERT INTO MEMBER (NAME, AGE, ID) VALUES ('김지형',25, 4);


UPDATE MEMBER SET AGE=35  WHERE id=3;



