SELECT * FROM emp;

SELECT * FROM DEPT;

-- AS 별칭 =>""
SELECT DNAME AS "부서 이름" FROM DEPT WHERE DEPTNO=20;

SELECT DNAME AS "부서 이름" FROM DEPT WHERE DEPTNO>=30;
-- order by 는 항상 맨 뒤에 작성 : 조회 후 정렬
SELECT ENAME, SAL FROM EMP WHERE SAL>=1000 AND SAL<2000 ORDER BY SAL DESC;

SELECT * FROM EMP WHERE ENAME='ALLEN';

UPDATE EMP SET SAL=2000 WHERE EMPNO=7499;

SELECT ENAME, SAL FROM EMP WHERE SAL BETWEEN 1000 AND 1999.99 ORDER BY SAL DESC;

-- 거의 대부분의 db는 날짜를 문자열로 조회 가능(자동파싱 "13"=>13, "{a:10}"=>{a:10})
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE>'1981-09-01';
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE='1987-07-13';
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE='1987-7-13';
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE>='1981-09-01' AND HIREDATE<'1981-10-01';
-- SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE='1981-09';
-- oralce은 지원하지 않음
-- BETWEEN A AND B : 수
-- BETWEEN DATE A AND DATE B : 날짜
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE BETWEEN '1981-09-01' AND  '1981-09-30';

-- TU???
SELECT * FROM EMP WHERE ENAME='TU';
SELECT * FROM EMP WHERE ENAME like 'TU%';
SELECT * FROM EMP WHERE ENAME like '%NE%';
SELECT * FROM EMP WHERE ENAME like '____';
SELECT * FROM EMP WHERE ENAME like '__RD';





