SELECT * FROM EMP WHERE COMM=null;
-- null 은 없는 데이터기 때문에 동등비교연산 불가
SELECT * FROM EMP WHERE COMM IS NULL;
SELECT * FROM EMP WHERE COMM IS NOT NULL;

-- 부서 20 이거나(또는) 30인 사원
SELECT * FROM EMP WHERE DEPTNO=20 OR DEPTNO=30;
SELECT * FROM EMP WHERE DEPTNO IN (20, 30);
SELECT * FROM EMP WHERE DEPTNO NOT IN (20, 30);

SELECT * FROM EMP WHERE COMM>0;
SELECT ENAME 이름, DEPTNO 부서번호, HIREDATE 입사일 FROM EMP  WHERE JOB='MANAGER';
