-- 출력만 해보는 것 => 가상테이블 dual

ALTER SESSION SET TIME_ZONE = 'Asia/Seoul';
SELECT SESSIONTIMEZONE FROM DUAL;

SELECT SYSDATE FROM DUAL;
SELECT SYSTIMESTAMP FROM DUAL;
SELECT CURRENT_TIMESTAMP FROM DUAL;
SELECT TO_CHAR(SYSDATE) FROM DUAL;
SELECT SYSTIMESTAMP AT TIME ZONE 'Asia/Seoul' FROM DUAL;
SELECT SYSDATE AT TIME ZONE 'Asia/Seoul' FROM DUAL;
SELECT TO_CHAR(SYSDATE,'HH24/MI/SS') FROM DUAL;
SELECT TO_CHAR(SYSDATE,'HH24"시" MI"분" SS"초"') FROM DUAL;


SELECT TO_NUMBER('12345')*3 FROM DUAL;
SELECT '12345'*3 FROM DUAL;

SELECT '12,345'*3 FROM DUAL;
SELECT TO_NUMBER('12,345','99G999')*3 FROM DUAL;

-- SELECT SAL+'$' FROM EMP;
-- SELECT ENAME+'님' FROM EMP;
SELECT ENAME || '님' FROM EMP;
SELECT CONCAT(ENAME,'님') FROM EMP;
SELECT SAL+10 FROM EMP;
SELECT SAL || '$' FROM EMP;
ALTER SESSION SET NLS_TERRITORY = 'AMERICA';
SELECT TO_CHAR(SAL,'FM999,999,999,999.00L' ) FROM EMP;
