SELECT LOWER(ENAME) FROM EMP;
SELECT INITCAP(ENAME) FROM EMP;
-- to_char, number, cast
SELECT SUBSTR(ENAME,1,1) FROM EMP;

SELECT SUBSTR('ORACLE',2,3) FROM DUAL;
-- 오라클의 배열 인덱스는 1 부터 시작
SELECT LENGTH(ENAME) FROM EMP;

SELECT CONCAT(ENAME,' 님') FROM EMP;
SELECT ENAME || ' 님' || ' 안녕하세요!' FROM EMP;
-- 1235
SELECT ROUND(1234.567) FROM DUAL;
SELECT ROUND(1234.567,1) FROM DUAL;
SELECT FLOOR(1234.567) FROM DUAL;
SELECT FLOOR(-0.1) FROM DUAL;

SELECT TRUNC(1234.567) FROM DUAL;
SELECT TRUNC(1234.567,2) FROM DUAL;
SELECT TRUNC(-0.1) FROM DUAL;
-- SELECT 2**3 FROM DUAL;
SELECT POWER(2,10) FROM DUAL;

-- SELECT 10%4 FROM DUAL;
SELECT MOD(10,4) FROM DUAL;

SELECT 10+10 FROM DUAL;
SELECT 10*10 FROM DUAL;
SELECT 10/3 FROM DUAL;
-- SELECT 10/0 FROM DUAL;
-- SELECT 10=10 FROM DUAL;
-- SELECT 10==10 FROM DUAL;
SELECT * FROM EMP WHERE SAL=800;
-- decode()
SELECT * FROM EMP WHERE SAL!=800;
SELECT * FROM EMP WHERE SAL<>800;
-- <> 같지않다의 옛날 문법
ALTER SESSION SET TIME_ZONE ='Asia/Seoul';
-- os의 시간
SELECT SYSDATE FROM DUAL;
SELECT SYSTIMESTAMP FROM DUAL;
-- oracle의 시간
SELECT CURRENT_DATE FROM DUAL;
SELECT CURRENT_TIMESTAMP FROM DUAL;

SELECT ADD_MONTHS(SYSDATE, 6) FROM DUAL;
SELECT ADD_MONTHS(SYSDATE, -8) FROM DUAL;
SELECT ADD_MONTHS(SYSDATE, -8) FROM DUAL;
SELECT SYSDATE-'2025-01-25 02:56:41' FROM DUAL;
SELECT SYSDATE-TO_DATE('2025-01-25 02:56:41','YYYY-MM-DD HH24:MI,SS') FROM DUAL;
SELECT SYSDATE-DATE '2025-01-25' FROM DUAL;
SELECT SYSDATE-CAST('2025-01-25' AS DATE) FROM DUAL;
-- 일수
SELECT MONTHS_BETWEEN(SYSDATE,'2025-01-25') FROM DUAL;
SELECT NEXT_DAY(SYSDATE,'일요일') FROM  DUAL;

-- NVL Null VaLue
SELECT ENAME, SAL, COMM, SAL+COMM 총급여 FROM EMP;
-- Null+수=Null
SELECT ENAME, SAL, COMM, SAL+NVL(COMM,0) 총급여 FROM EMP;
-- NVL2(COMM,Y,N)
-- 커미션을 받으면 YES, 받지않으면 NO
SELECT ENAME,NVL2(COMM,'YES','NO') 커미션유무 FROM EMP;
-- switch(deptno){
--      case 10 : 'ACCOUNTING'
-- }
SELECT ENAME,
       DECODE(DEPTNO,
              10,'ACCOUNTING',
              20,'RESEARCH',
              30,'SALES') AS 부서이름
    FROM EMP;
SELECT * FROM DEPT;
-- 10,ACCOUNTING,NEW YORK
-- 20,RESEARCH,DALLAS
-- 30,SALES,CHICAGO
-- 40,OPERATIONS,BOSTON