SELECT SUM(sal) FROM EMP;
-- SELECT ENAME, SUM(sal) FROM EMP;
SELECT SUM(sal) as "급여의 총합", ROUND(AVG(SAL)) as "급여의 평균" FROM EMP;
-- 집계함수를 작성하면 필드는 꼭 직계함수만 작성 가능!
-- distinct : 중복제거 (집계아님)
SELECT DEPTNO FROM EMP;
SELECT DISTINCT DEPTNO FROM EMP;
UPDATE EMP SET COMM=NULL WHERE COMM=0;
SELECT COUNT(*),MAX(sal),MAX(comm),MIN(SAL),MIN(COMM) FROM EMP;
SELECT COUNT(*),MAX(sal),MAX(comm),MIN(SAL),MIN(COMM) FROM EMP WHERE DEPTNO=10;
SELECT COUNT(*),MAX(sal),MAX(comm),MIN(SAL),MIN(COMM) FROM EMP WHERE DEPTNO=30;
SELECT STDDEV(SAL) FROM EMP;

SELECT DISTINCT DEPTNO FROM EMP;
-- 집계를 그룹간 group by
SELECT DEPTNO, SUM(SAL),ROUND(AVG(SAL)) FROM EMP GROUP BY DEPTNO;


-- SELECT DEPTNO, SUM(SAL),ROUND(AVG(SAL)) FROM EMP  GROUP BY DEPTNO WHERE SAL>1000;
-- SELECT DEPTNO,
--        SUM(SAL) AS TOTAL,
--        ROUND(AVG(SAL)) AS AVG
--     FROM EMP
--     WHERE SAL>=1000 AND TOTAL>8500
--     GROUP BY DEPTNO;
SELECT DEPTNO,
       SUM(SAL) AS total
    FROM EMP
    GROUP BY DEPTNO
    HAVING SUM(SAL)>9000
    ORDER BY total ASC;

