SELECT * FROM EMP;
-- 사원관리페이지서 페이징이되어 있어있음
-- 한 페이지당 5명씩 출력
SELECT ROWNUM no, e.* FROM EMP e ORDER BY e.HIREDATE;

-- SELECT ROWNUM no,emp.* FROM(SELECT * FROM EMP ORDER BY HIREDATE) emp
-- WHERE no BETWEEN 1 AND 5;
-- ????
SELECT * FROM (SELECT ROWNUM no,emp.* FROM(SELECT * FROM EMP ORDER BY HIREDATE) emp)
WHERE no BETWEEN 11 AND 15;
-- row 5
--  1  1~5    (page-1)*5+1 ~ (page)*5
--  2  6~10
--  3  11~15


SELECT ROWNUM, e.* FROM EMP e ORDER BY SAL;

-- OVER

SELECT * FROM(SELECT ROW_NUMBER() OVER (ORDER BY SAL) no, e.* FROM EMP e)
WHERE no BETWEEN 11 AND 15;

-- offset!!!!
SELECT *
    FROM EMP
    ORDER BY SAL
    OFFSET 10 ROWS FETCH NEXT 5 ROWS ONLY;
