SELECT * FROM EMP;
-- 1000 게이글
-- 최근에 등록된 글 10개 1 page
-- 최근에 등록된 글 10개 다음 10개 2 page
-- ... pagination, paging

-- 입사일이 가장 최근인 사원을 5명씩 본다. paging
SELECT * FROM EMP ORDER BY HIREDATE DESC;
-- ROWNUM : 행에 번호를 매김
SELECT ROWNUM as no,EMP.* FROM EMP;
SELECT ROWNUM as no,
       EMP.*
    FROM EMP
    ORDER BY HIREDATE DESC;
-- ROWNUM 은 정렬 이정에 번호를 매기기 때문에...
SELECT ROWNUM no,e.*
FROM (SELECT * FROM EMP ORDER BY HIREDATE DESC) e
WHERE no BETWEEN 5 AND 10;
-- ROWNUM 은 where 절이 끝이나고 실행
-- WHERE 절에서 ROWNUM 함수 자체를 호출하면 select의 ROWNUM과 동시에 실행
SELECT * FROM(SELECT ROWNUM as no ,e.*
    FROM (SELECT * FROM EMP ORDER BY HIREDATE DESC) e
    WHERE ROWNUM <=10)
WHERE no>5;
--     WHERE ROWNUM BETWEEN 5 AND 10;
SELECT * FROM(SELECT ROWNUM as no ,e.*
              FROM (SELECT * FROM EMP ORDER BY HIREDATE DESC) e)
WHERE no BETWEEN 6 AND 10;


-- 급여의 평균보다 급여를 많이 받는 사람
-- MAX MIN AVG ...
SELECT AVG(SAL) FROM EMP;

SELECT * FROM EMP WHERE SAL>(SELECT AVG(SAL) FROM EMP);

SELECT e.*,
       (SELECT AVG(SAL) FROM EMP WHERE DEPTNO=e.DEPTNO) 평균
FROM EMP e;

SELECT ROWNUM no,EMP.* FROM EMP WHERE no BETWEEN 5 AND 10;
SELECT * FROM (SELECT ROWNUM no,EMP.* FROM EMP) WHERE no BETWEEN 5 AND 10;

SELECT ROWNUM,EMP.* FROM EMP ORDER BY SAL DESC;
-- mysql db : 서브쿼리의 가상테이블의 가명,별칭을 꼭 붙여야함
SELECT * FROM (
    SELECT ROWNUM no,e.* FROM (SELECT * FROM EMP ORDER BY SAL DESC) e
    WHERE ROWNUM <= 10)
WHERE no>5;
-- 성능 X, 번호 X, 오직 코드만 짧게
-- (page-1)*row
SELECT * FROM EMP ORDER BY SAL DESC
OFFSET 10 ROWS FETCH NEXT 5 ROWS ONLY;

-- row:5 page:3 (page-1)*row
SELECT * FROM PAY_HISTORY
OFFSET 10 ROWS FETCH NEXT 5 ROWS ONLY;

-- page*row
SELECT *
FROM(SELECT ROWNUM no,PAY_HISTORY.* FROM PAY_HISTORY WHERE ROWNUM<=15)
WHERE no>=11;

SELECT * FROM PAY_HISTORY p,EMP e WHERE p.EMPNO=e.EMPNO;

SELECT * FROM(SELECT ROWNUM no,ph.* FROM (SELECT *
    FROM PAY_HISTORY p INNER JOIN EMP e
        ON p.EMPNO=e.EMPNO
    WHERE DEPTNO=10 ORDER BY AMOUNT DESC) ph WHERE ROWNUM<=10)
WHERE no>=6;


SELECT * FROM PAY_HISTORY WHERE EMPNO IN (
    SELECT EMPNO FROM EMP WHERE DEPTNO=10
);
SELECT * FROM PAY_HISTORY p WHERE EXISTS(
    SELECT * FROM EMP e WHERE e.EMPNO=p.EMPNO AND DEPTNO=10
);


-- row_number() over()

SELECT PAY_HISTORY.*, AVG(AMOUNT) OVER () FROM PAY_HISTORY;
-- rank,row_number() : top-n stop-key 로 중간에 번호 매기는 것을 멈출수 없다.
SELECT ROW_NUMBER() over (ORDER BY PAY_DATE DESC) no, p.* FROM PAY_HISTORY p;

SELECT ROWNUM no,p.* FROM(SELECT * FROM PAY_HISTORY ORDER BY PAY_DATE) p
WHERE ROWNUM<10;

SELECT * FROM(
    SELECT
        ROW_NUMBER() over (ORDER BY PAY_DATE DESC) no,
        p.*
    FROM PAY_HISTORY p)
WHERE no BETWEEN 11 AND 15;

SELECT * FROM(
     SELECT
         ROW_NUMBER() over (ORDER BY AMOUNT DESC) no,
         p.*
     FROM PAY_HISTORY p)
WHERE no BETWEEN 6 AND 10;

SELECT * FROM(
    SELECT
        ROW_NUMBER() over (ORDER BY BONUS DESC) no,
        p.*
    FROM PAY_HISTORY p
    WHERE BONUS IS NOT NULL)
WHERE no BETWEEN 6 AND 10;


--  1page 0~ 5개
SELECT *
FROM PAY_HISTORY
ORDER BY PAY_DATE DESC
OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY;

SELECT *
FROM PAY_HISTORY
ORDER BY AMOUNT DESC
OFFSET 5 ROWS FETCH NEXT 5 ROWS ONLY;

SELECT *
FROM PAY_HISTORY
WHERE EMPNO IN (
    SELECT EMPNO
    FROM EMP
    WHERE JOB='SALESMAN')
OFFSET 5 ROWS FETCH NEXT 5 ROWS ONLY;
-- 오늘은 2025-02-02
SELECT * FROM PAY_HISTORY
WHERE ABS(PAY_DATE- DATE '2025-02-02')<=30
ORDER BY PAY_DATE DESC
OFFSET 0 ROWS FETCH NEXT 5 ROWS ONLY ;

SELECT CURRENT_DATE - CAST('2025-09-01' as DATE) FROM DUAL;


UPDATE EMP SET SAL=6000 WHERE ENAME='KING';
SELECT * FROM EMP;
COMMIT;

