SELECT * FROM EMP;
SELECT EMPNO,ENAME,SAL FROM EMP;
SELECT EMPNO,ENAME,SAL,평균 FROM EMP,(SELECT AVG(SAL) 평균 FROM EMP);
SELECT EMPNO,ENAME,SAL,AVG(SAL) OVER () 평균 FROM EMP;

SELECT EMPNO,ENAME,SAL,AVG(SAL) OVER (PARTITION BY DEPTNO) 평균
    FROM EMP
    ORDER BY EMPNO;

SELECT EMPNO,ENAME,SAL,평균
    FROM EMP e,(SELECT DEPTNO, AVG(SAL) 평균 FROM EMP GROUP BY DEPTNO) a
    WHERE e.DEPTNO=a.DEPTNO
    ORDER BY EMPNO;

SELECT RANK() over (ORDER BY SAL DESC),e.SAL,e.ENAME FROM EMP e;
SELECT DENSE_RANK() over (ORDER BY SAL DESC),e.SAL,e.ENAME FROM EMP e;

SELECT * FROM (SELECT DENSE_RANK() over (PARTITION BY DEPTNO ORDER BY SAL DESC) as rank
     ,e.DEPTNO,e.SAL,e.ENAME
FROM EMP e)
WHERE rank<=3;



