SELECT * FROM EMP WHERE SAL>=2000;

CREATE VIEW EMP_2000_SAL AS SELECT * FROM EMP WHERE SAL>=2000;

SELECT * FROM EMP_2000_SAL;

CREATE VIEW EMP_DEPT AS
SELECT EMP.*,DEPT.DNAME,DEPT.LOC
FROM EMP LEFT JOIN DEPT
    ON EMP.DEPTNO=DEPT.DEPTNO;

SELECT * FROM EMP_DEPT;
-- create DDL
DROP VIEW EMP_2000_SAL;
-- Grant Revote DCL
-- SELECT(DQL),I,D,U DML
-- JDB